repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-added-large-files
        exclude: yarn.lock
      - id: check-case-conflict
      - id: check-executables-have-shebangs
        files: \.sh
      - id: check-json
      - id: check-vcs-permalinks
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: prettier
        name: Prettier
        language: system
        files: \.(j|t)sx?$
        entry: bash -c 'yarn format'
        pass_filenames: false
  - repo: local
    hooks:
      - id: eslint
        name: ESLint
        language: system
        files: \.(j|t)sx?$
        entry: bash -c 'yarn lint'
        pass_filenames: false
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.12.0
    hooks:
      - id: gitlint
